### ISSUE TITLE
Raspberry Pi 5: Unable to load 'jingle_peerconnection_so' library.

### ISSUE THREAD

**Issue by DedSecMF** [MekayelAnik/ispyagentdvr-docker#10]
### OS Details:
- Debian version: 12 (bookworm)
- Linux 6.1.0-rpi8-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux
- Docker version: Docker version 25.0.2, build 29cf629

### Problem:
I attempted to set up iSPY using Docker on my Raspberry Pi 5, but encountered the following error:

`This docker image was built at: Wed Feb  7 06:13:32 +06 2024 : Bangladesh Time (UTC+06)`
`This Container was started on: Wed Feb  7 07:45:20 EST 2024`
`Unhandled exception. System.TypeInitializationException: The type initializer for 'Pixiv.Rtc.ThreadManager' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'jingle_peerconnection_so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libjingle_peerconnection_so: cannot open shared object file: No such file or directory
   at Pixiv.Rtc.ThreadManager.rtcThreadManagerInstance()
   at Pixiv.Rtc.ThreadManager..cctor()
   --- End of inner exception stack trace ---
   at Pixiv.Rtc.ThreadManager.get_Instance()
   at CoreLogic.Server.WebRTC.RTCConnection.RunTURN()
   at System.Threading.Thread.StartCallback()
/AgentDVR/Agent.sh: line 8:    14 Aborted                 (core dumped) /AgentDVR/Agent`

### Additional Information:
- I've tried installing directly on my Raspberry Pi without docker, but the issue persists.

**Comment by MekayelAnik** [comment]
As far as I know there are some bugs in the latest Raspbian for Raspi 5.
Try Installing [Ubuntu](https://ubuntu.com/download/raspberry-pi) as your OS.
Then install docker on it and deploy container on it.
Please give update.
Regards
