### ISSUE TITLE
Crashes when trying to encode in h264 or h265.  CPU and GPU.

### ISSUE THREAD

**Issue by Diviance** [MekayelAnik/ispyagentdvr-docker#12]
It will immediately crash if I tell it to record into h264 or h265.  GPU or GPU, Intel QSV/VAAPI or Nvidia GPU.

This is using the GPU or VLC+GPU tags.  I did not test with CPU only because, well... CPU encoding takes way more power.

**Comment by MekayelAnik** [comment]
Logs?

**Comment by Diviance** [comment]
Well, here is what hitting the copy button says after I try telling it to record.

`free(): double free detected in tcache 2
/AgentDVR/Agent.sh: line 28:    17 Aborted                 /AgentDVR/Agent`

And I will add an image showing the Unraid container settings for it.
![Screenshot 2024-03-16 224734](https://github.com/MekayelAnik/ispyagentdvr-docker/assets/950770/b6d6e43b-c915-46db-8a51-4899d06af18f)

**Comment by MekayelAnik** [comment]
I had this error when my Drive became Read-Only.
I think the directory u set for recording is either have no space left(this is the most probable cause) or your directory path is Read-Only (Not writeable).

**Comment by Diviance** [comment]
If that were the case (and it has roughly 22TB available), why would it be able to write out Raw, VP8 and VP9 when that is the only change made?

Though none of the GPU encoding seems to work.  But one problem at a time.

**Comment by MekayelAnik** [comment]
Yes you are right, there are definitely Big issues in Encoding section. I have always used RAW recording thus never encountered this.
I think this is not a issue of the container image but iSpy AgentDVR itself. 
Have u passed your Intel iGPU to the Container? Hardware Accelerated VP9 & VP8 should work on Intel GPU else will throw some error like it did in the case of h264 & h265.
If you have passed the Intel iGPU to the container please provide the full log (From Starting till the Crash) by entering: AgentDVR-IP:8090/logs.html in a browser.
I hope the Dev Team of iSpy will have a look into this.

**Comment by Diviance** [comment]
CUDA, VAAPI and QSV all fail with near identical errors.  Here is the one for VAAPI (and QSV, since it tries both) using the iGPU.

7:16:36 PM	FFmpeg: error: [AVHWDeviceContext @ 0x1456d402cd40] Failed to initialise VAAPI connection: -1 (unknown libva error).
7:16:36 PM	FFmpeg: error: [vp9_vaapi @ 0x1456d4049b00] No usable encoding entrypoint found for profile VAProfileVP9Profile0 (19).
7:16:36 PM	FD-PTZ: TryOpenVideoCodec: Writer: Open Codec:Function not implemented at CoreLogic.RealTime.FFmpegBase.Throw(String method, Int32 code) at CoreLogic.RealTime.MediaWriter.TryOpenVideoCodec(AVCodecID baseCodec, String encoder)
7:16:36 PM	FD-PTZ: GetVideoCodec: Can't open vp9_vaapi for AV_CODEC_ID_VP9
7:16:36 PM	FD-PTZ: TryOpenVideoCodec: Object reference not set to an instance of an object. at CoreLogic.RealTime.MediaWriter.ConfigureQSVEncoder() at CoreLogic.RealTime.MediaWriter.TryOpenVideoCodec(AVCodecID baseCodec, String encoder)
7:16:36 PM	FD-PTZ: GetVideoCodec: Can't open vp9_qsv for AV_CODEC_ID_VP9
7:16:36 PM	FD-PTZ: GetVideoCodec: vp9_cuvid Not found
7:16:36 PM	FD-PTZ: TryOpenVideoCodec: Object reference not set to an instance of an object. at CoreLogic.RealTime.MediaWriter.ConfigureQSVEncoder() at CoreLogic.RealTime.MediaWriter.TryOpenVideoCodec(AVCodecID baseCodec, String encoder)
7:16:36 PM	FD-PTZ: GetVideoCodec: Can't open vp9_qsv for AV_CODEC_ID_VP9
7:16:36 PM	FD-PTZ: GetVideoCodec: Disabling GPU encode - use raw recording for max performance
7:16:36 PM	FD-PTZ: HandleRecorderRecordingOpenedAsync: Recording Opened
7:16:36 PM	FD-PTZ: HandleRecorderRecordingOpenedAsync: Recording Created
7:16:36 PM	FD-PTZ: HandleRecorderRecordingOpenedAsync: New Recording Notified

**Comment by Diviance** [comment]
As an addendum, if I use the doitandbedone/ispyagentdvr container (well, that container but edited to use the same version of Agent DVR, no other changes as your container)... it _will_ record in both h264 and h265... but it has no GPU support at all, so yeah.  I don't know.

**Comment by MekayelAnik** [comment]
Thank you, My AgentDVR just crashes on my AMD gpu when it tries to encode.
U have passed the intel GPU to the container right?
I am asking because, in the case of QSV, there is no Entrypoint found.
Have u add the:
```
devices:
    - /dev/dri/renderD128:/dev/dri/renderD128
    - /dev/dri/card0:/dev/dri/card0
```
???
Anyways I hope **Sean** will have a look into this.
This is way out of my expertise & scope. As far as I can tell the errors are thrown from #C code. So iSpy AgentDVR it self is throwing the error.

**Comment by Diviance** [comment]
I did it both being specific, like that, and simply passing through the /dev/dri part (which works in Tdarr, Plex and other containers on the same machine).

**Comment by ispysoftware** [comment]
You can't just drop a different version of ffmpeg in there and assume it will work ok - it needs to be a version match for the version that ffmpeg.autogen.dll was built against otherwise parts of the code will be calling invalid locations in memory in the ffmpeg libraries. - at the moment that's 6.0.0.2

Agent doesn't use the ffmpeg command line it uses ffmpeg's API via a c# wrapper that is version matched.

I've run it here with the right ffmpeg build and it doesn't crash. "Function not implemented" is a sign that it's not calling into the right locations in the libraries.

**Comment by ispysoftware** [comment]
this specific error is a bug in ffmpegs code
https://code.videolan.org/videolan/vlc/-/issues/27551
i'll need to add the encoder into the UI instead of auto trying the borked amf encoder

**Comment by Diviance** [comment]
Ah, I didn't even consider it was using a wrapper.  That explains a lot.

I don't really know where else to ask, and since I have your eye... I see that 5.3.2.0 (and probably some previous versions), it grabs a copy of ffmpeg6 from the agent dvr site and uses that in the other docker for agentdvr.  Would it be possible to get a version of that ffmpeg built that supports nvenc/cuda and qsv/vaapi hardware acceleration for encoding and decoding?  Because it doesn't appear to have that in my test.

**Comment by ispysoftware** [comment]
you can build it - the windows version works with nvenc/ cuda 
this one (jellyfin) will probably work if they fix that bug or i can just ignore the AMF encoder

**Comment by Diviance** [comment]
Windows version won't really help, AgentDVR is running in a docker container on Unraid.  Are you saying the wrapper only checks the actual version of ffmpeg, not all of its functionality?  So as long as the built version is 6.0.0.2, it will work?  Because I can probably manage that.

**Comment by ispysoftware** [comment]
Yeah if you want to wait a day or 2 will prob have a fix

**Comment by Diviance** [comment]
Sure, I can wait.  I appreciate the help and information.

**Comment by ispysoftware** [comment]
Updated files
https://drive.google.com/file/d/1aXKXXM8A4j9qlnQEWxzQney6SdocEQYZ/view?usp=sharing

- see recording tab, set codec in advanced to h264_qsv or h264_vaapi. If it fails you'll get an error message at the top of the recording tab.
- you might need to specify the hardware device to use under  Encode Device to /dev/dri/renderD128 or something (I don't have the hardware here to test it)
- set the logs under server settings - logging to debug for Agent and Verbose for ffmpeg if you have issues

I think the h264_amf encoder is broken in this (jellyfin) ffmpeg build - so choosing that is likely to break it.

None of this works on my windows 11 box. I'm not sure why as I've forwarded the GPU into the container. I just get errors like:

11:10:19 AM | FFmpeg: verbose: [AVHWDeviceContext @ 0x7fec240c7e80] Cannot open DRM render node for device 0.

I found a similar issue on jellyfin with a fix but unsure how to apply it:
https://github.com/linuxserver/docker-jellyfin/issues/26#issuecomment-618089750

**Comment by Diviance** [comment]
Ok.  This doesn't immediately crash when I try to record using h264 or h265.  Now I need to find or build a copy of ffmpeg 6.0.2 with proper hardware acceleration support and I think it should work.  I will look into that tomorrow.

**Comment by ispysoftware** [comment]
you might be able to use the jellyfin one that's in the gpu test build

**Comment by MekayelAnik** [comment]
New test image (x86_64 Only) deployed for testing:
docker pull mekayelanik/ispyagentdvr:gpu-hwaccel-5.3.3.0-test-145119032024

**Comment by ispysoftware** [comment]
updated
https://drive.google.com/file/d/1ZmWg5uAosnRaunFNp9gisCswG5Xzmdiw/view?usp=drive_link
fixed issue with audio, removed xxx_amf encoder on linux
https://github.com/jellyfin/jellyfin-ffmpeg/issues/210#issuecomment-1416761768

**Comment by MekayelAnik** [comment]
New test image (x86_64 Only) deployed for testing:
docker pull mekayelanik/ispyagentdvr:gpu-hwaccel-5.3.3.0-test-064820032024

**Comment by ispysoftware** [comment]
Found a QSV encode capable computer and got it working (in Windows at least)
Uploaded an update (same link above)

**Comment by MekayelAnik** [comment]
New test image (x86_64 Only with QSV Update) deployed for testing
docker pull mekayelanik/ispyagentdvr:gpu-hwaccel-5.3.3.0-test-153820032024

**Comment by MekayelAnik** [comment]
All the known GPU HARDWARE ACCELERATED Encoder/Decoder related issues till this date, have been solved in v5.3.3.0
Please use image equal or newer than `mekayelanik/ispyagentdvr:gpu-hwaccel-5.3.3.0`
Special shout out to **Sean** from **iSpy Software**

**Comment by MekayelAnik** [comment]
@Diviance can you please check the status of HWACCEL Encode/Decode on Nvidia GPU also as u did in the case of QSV? I am placing this request as u the Issue very well & also u have a Nvidia GPU.
It will be great if u leave a feedback.
Thank you for your participation & report of the issue.

**Comment by Diviance** [comment]
Ok, sorry for the delay, it has been a week for me.  Haven't really had time to mess with my server.

I updated to the latest image you posted up there and both QSV and NVENC appear to be working just fine for me.  I did not see any errors in the logs when recording or doing playback using cuda/nvenc.

**Comment by MekayelAnik** [comment]
@Diviance
Thank you for your Sincere feedback.
Regards
