### ISSUE TITLE
Media folder incorrect

### ISSUE THREAD

**Issue by nicktayl88** [MekayelAnik/ispyagentdvr-docker#17]
Since updating recordings are now being saved to:

/agent/Media/WebServerRoot/Media
not
/AgentDVR/Media/WebServerRoot/Media

Is this the correct behaviour?

**Comment by MekayelAnik** [comment]
No, it's not the correct behaviour. Mine is working fine and saving recording Video files in `/AgentDVR/Media/WebServerRoot/Media`
Which image you are using? Please share your Docker CLI command or Docker Compose file you are using to deploy the AgentDVR on Docker in your system.

**Comment by MekayelAnik** [comment]
Closing the issue due to lack of information & follow up.
