### ISSUE TITLE
How to aksess media folders in docker for linux?

### ISSUE THREAD

**Issue by rogerbl** [MekayelAnik/ispyagentdvr-docker#18]
I'm running docker on an ubuntu server and would like to aksess the media folders.
Where in linux do I find this folder?

**Comment by MekayelAnik** [comment]
Dear @rogerbl,
Please visit: [Dockerhub/ispyagentdvr](https://hub.docker.com/repository/docker/mekayelanik/ispyagentdvr/) page. You will find all the required details there. Read the documentations carefully. I hope you will find the documentation helpful.

Also please don't open an issue in github, if the thing you want is just a specific information. If you are new to Docker or ispy AgentDVR, Please visit the [Reddit](https://www.reddit.com/r/ispyconnect/) & open a Reddit Post there, you will find many good people, who will help you to solve your issue or show you the correct path to take,

Regards
