### ISSUE TITLE
Storage leak?

### ISSUE THREAD

**Issue by chriexpe** [MekayelAnik/ispyagentdvr-docker#2]
Yesterday I found your repo and decided to give a try after only using doitandbedone/ispyagentdvr image (whoever manages it take ages to update :latest flag), as I was using Froodle's template on Unraid, I needed to change all the volumes from "agent" to "AgentDVR" for it to work properly, and it did, except later I realized that my docker.img was filling too fast, and after checking what docker was  doing that, it was yours, but did I mistype something? I checked all volumes and they are the same from your instructions.

```
root@chriexpe:~# docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          28        26        19.48GB   2.777GB (14%)
Containers      29        18        3.232GB   46.81MB (1%)
Local Volumes   266       7         253.7MB   253.6MB (99%)
Build Cache     2         0         0B        0B
```

*after a  couple of seconds*

```
root@chriexpe:~# docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          28        26        19.48GB   2.777GB (14%)
Containers      29        18        4.115GB   46.81MB (1%)
Local Volumes   266       7         253.7MB   253.6MB (99%)
Build Cache     2         0         0B        0B
```

*after stoppping AgentDVR container*

```
root@chriexpe:~# docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          28        26        19.48GB   2.777GB (14%)
Containers      29        17        4.404GB   3.406GB (77%)
Local Volumes   266       7         253.7MB   253.6MB (99%)
Build Cache     2         0         0B        0B
```

This is the docker run/Unraid config:

```
docker run
  -d
  --name='Agent-DVR'
  --net='br0'
  --ip='192.168.0.205'
  -e TZ="America/Sao_Paulo"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="chriexpe.server"
  -e HOST_CONTAINERNAME="Agent-DVR"
  -e 'TCP_PORT_8090'='8090'
  -e 'UDP_PORT_3478'='3478'
  -e 'TCP_PORT_50000'='50000-50010'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8090]'
  -l net.unraid.docker.icon='https://ispycontent.azureedge.net/img/ispy2.png'
  -v '/mnt/user/appdata/agentDVR/config':'/AgentDVR/Media/XML/':'rw'
  -v '/mnt/nasa/nvr/':'/AgentDVR/Media/WebServerRoot/Media/':'rw'
  -v '/mnt/user/appdata/agentDVR/commands':'/AgentDVR/Commands':'rw'
  --restart=unless-stopped
  --dns 8.8.8.8
  --dns 1.1.1.1 'mekayelanik/ispyagentdvr:latest' 
```

**Comment by chriexpe** [comment]
Update:
I've found the issue, as I've only changed the repo to this one (and docker path), the settings where still from the old one, so what happens is, even though the docker run/compose of this image says that the internal path to recordings is "/AgentDVR/Media/WebServerRoot/Media", at the settings on AgentDVR it still was at /agent/Media/WebServerRoot/Media/.

**Comment by MekayelAnik** [comment]
I am glad you have found the culprit.
The media dir is set in the conf file. It can be changed to any dir at anytime. If the media dir is changed then the docker volume must be mapped according. Same goes to the WebUI port. If you change the port in the sever settings which saves tge settings in the conf file, you will be able to access the webui on that port.
