### ISSUE TITLE
Latest docker image fails to run on Pi4

### ISSUE THREAD

**Issue by thoja21** [MekayelAnik/ispyagentdvr-docker#20]
I'm having a hard time getting AgentDVR to run within Docker.

I'm trying to run it on a Raspberry Pi 4 (8GB) using the latest version of docker using docker compose.

I've adapted the example in the docs & readme (see attached).
However AgentDVR aborts with no logs or reason - at least none that I can find.

[docker-compose.yml.txt](https://github.com/MekayelAnik/ispyagentdvr-docker/files/15314588/docker-compose.yml.txt)

The output I see from the container and AgentDVR starting is also attached.
[output.txt](https://github.com/MekayelAnik/ispyagentdvr-docker/files/15314592/output.txt)

I've checked paths to volumes and permissions.
The config folder is empty. This is a clean setup. No other containers running.

Anything else I can check? Or any other information I can provide?

**Comment by MekayelAnik** [comment]
Sorry for the late reply.
Are you still facing the same problem in version 5.5.4.0?
BTW, your time was WAYYYY off. Have you corrected your host time? Your host machine time must be accurate. The container was reporting year: 1970. Which is odd, don't u think?
If you are still facing the problem after the fixes please leave follow up.

Regards

**Comment by MekayelAnik** [comment]
Closing due to lack of response.
