### ISSUE TITLE
Unable to load shared library 'cvextern'

### ISSUE THREAD

**Issue by ylexus** [MekayelAnik/ispyagentdvr-docker#24]
Using docker image, version 5.5.7.0 on Raspberry Pi. Configured a camera but can't see the live stream. There's an error in the log. It was supposed to have been fixed a few versions ago. Please help. 

```
00:25:25	Camera 1: DoStart: Using tcp Transport
00:25:28	Camera 1: SetupDecoder: Found decoder AV_HWDEVICE_TYPE_VAAPI
00:25:28	Camera 1: SetupDecoder: Opening AV_HWDEVICE_TYPE_VAAPI
00:25:28	Camera 1: FailHW: Couldn't create AV_HWDEVICE_TYPE_VAAPI decoder. Using CPU instead.
00:25:28	Camera 1: SetupFormat: Using software decoder
00:25:29	Camera 1: ReadFrames: The type initializer for 'Emgu.CV.CvInvoke' threw an exception. at CoreLogic.Sources.Combined.MediaStream.ReadFrames()
00:25:29	Camera 1: ReadFrames: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object file: No such file or directory at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata) at Emgu.CV.CvInvoke..cctor()
00:25:29	Camera 1: SourcePlayingFinished: Playing finished (SourceError)
00:25:29	Camera 1: NextReconnectTarget: Reconnecting in 30s

```

**Comment by MekayelAnik** [comment]
<b> Please provide following informations so that I can work with: </b>
- Is the AgentDVR version v5.5.6.0, 5.5.5.0 & 5.5.4.0 working <b>FINE</b> on your Raspberry Pi?
- Which Raspberry Pi?
- What is the version of your raspbianOS?
- What is the Platform? (ARM64 or ARMHF?)
- What is the version of your docker engine? (If not latest please update to latest)

**Comment by ylexus** [comment]
Sure - here it is

Tried 5.5.6.0 - same problem. Will try the rest shortly.
Raspberry Pi 4 Model B Rev 1.2
Raspbian 10 (buster): Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux (32 bit - guess this is armhf)
Docker version 26.1.4, build 5650f9b - no upgrades available

**Comment by MekayelAnik** [comment]
Though off topic, I am suggesting you to move to a arm64 Bookworm (Preferably Dietpi).
Life is hard,don't make it harder.
There is also latest version 5.6.0.0 available. Please let me know if v5.5.4.0 & 5.6.0.0 is working or not.
I will have a look into the armhf image.

**Comment by ylexus** [comment]
Tried 5.5.5.0 and 5.5.4.0 - same issue.

**Comment by ylexus** [comment]
Thanks, there is no easy way to move a live rpi installation, let alone a highly customised one like mine, to a different major version of Raspbian. So in this context "making life hard" means the opposite to me than it is to you possibly.

**Comment by ylexus** [comment]
Same error on 5.6.0.0

**Comment by MekayelAnik** [comment]
@ispysoftware can you please have a look into the issue?
One or more dependencies are not met. Effected versions are 5.5.2.0 to 5.6.0.0 armhf builds. I think something is missing in the docker image build script from my side.
Can you show me a way to find whats missing?
Looking forward to your help.

**Comment by MekayelAnik** [comment]
Special thanks to @ispysoftware for helping me figuring out what was wrong.
Versions from 5.3.5.0 to 5.6.0.0 will be redeployed with fixs within 48 Hours from now.
Till then please use v5.0.0.0 for armhf.

**Comment by ylexus** [comment]
What an irony. I decided to upgrade to a 64 bit Raspbian, as you suggested, and then thought, since I am upgrading, let's also upgrade hardware from 4 to 5. So I bought a Raspberry Pi 5 and installed your image there only to get hit with https://www.reddit.com/r/ispyconnect/comments/1ayygp3/problems_with_agentdvr_on_raspberry_pi_5/ (https://github.com/MekayelAnik/ispyagentdvr-docker/issues/10). What a mess.

**Comment by MekayelAnik** [comment]
My bad. I thought that issue must have solved by now. Irony for Debian fans indeed.
Try Ubuntu latest for Raspi. Heard it performs gracefully.

**Comment by MekayelAnik** [comment]
All the images that is 5.3.5.0 or NEWER are fixed. These images are now working as intended on  ARM64, ARMHF & x86_64.
Thank you @ylexus for  your report.

Regards
