### ISSUE TITLE
Footage is saved under /agent rather than /AgentDVR

### ISSUE THREAD

**Issue by trinity-geology-unstable** [MekayelAnik/ispyagentdvr-docker#4]
I have external storage mounted to /AgentDVR/Media/WebServerRoot/Media/ within this container. However instead footage is saved to a Docker volume which grows in size until the system crashes.

If I instead mount to /agent/Media/WebServerRoot/Media/ within the container it works as expected and saves the footage to the mounted external storage.

I assume this is a holdover from the depreciated doitandbedone image because the /agent/ mount point was used in their image.

**Comment by MrDibbley** [comment]
might be related to your config.xml from the previous docker still pointing to:

`  <MediaDirectories>
    <Directory Entry="/agent/Media/WebServerRoot/Media/" EnableManagement="true" MaxSize="1000000" MaxAge="168" ArchiveDirectoryNew="" />
  </MediaDirectories>`

**Comment by trinity-geology-unstable** [comment]
Hi, this is correct. After amending my config the issue no longer persists.

**Comment by MekayelAnik** [comment]
You had persistent configs from the older image. I would be great if you backup the "Devices" and "layout" from the older image's container. Then spin up new Container with the new image. After that restore the Devices and Layout and you should good to go. The other settings should be edited manually as an user intends. I am sorry but how it is, as in this image the Working Directory is /AgentDVR ratger than /agent. 
This should be a one time thing. Later updates will not require this.
