### ISSUE TITLE
Issue on latest 5.1.0.0

### ISSUE THREAD

**Issue by alexbn71** [MekayelAnik/ispyagentdvr-docker#5]
![image](https://github.com/MekayelAnik/ispyagentdvr-docker/assets/20998190/18b0b779-ed8a-4fc3-a28e-a94d0cc117c4)

exit without any indication of error

**Comment by TobiasKWF** [comment]
Same Problem... Docker stops direct after upgrading with no messages or errors in docker log

**Comment by MekayelAnik** [comment]
@alexbn71 @TobiasKWF 

What is your platform? Mine is running fine on ARM64.

**Comment by boloj** [comment]
I'm having the same issue. Mine is running on Intel. I rolled back to the previous version and no longer had the issue.

**Comment by alexbn71** [comment]
> What is your platform? Mine is running fine on ARM64.

Mine AMD Ryzen. Same to me, the previous version still work fine

**Comment by technodeejay** [comment]
Exact same problem here too - something obviously broken in the new version. I too am on AMD Ryzen, Ubuntu, Docker.

Though mine does give an error: -

`/AgentDVR/Agent.sh: line 3: /AgentDVR/Agent: No such file or directory`

**Comment by MekayelAnik** [comment]
@alexbn71 @technodeejay @boloj @technodeejay 
I have taken down yesterday's image. Please remove that image using `docker rmi mekayelanik/ispyagentdvr:latest` or `docker rmi mekayelanik/ispyagentdvr:5.1.0.0` and redownload the "latest" or "5.1.0.0" using `docker pull mekayelanik/ispyagentdvr:latest` or `docker pull mekayelanik/ispyagentdvr:5.1.0.0`
One chmod missed execution while creating the image, don't know why, but it did. Should Work now.
Sorry for the inconvenience.
Regards

**Comment by technodeejay** [comment]
Can confirm, this has fixed the problem - thank you very much!
