### ISSUE TITLE
Lack of intel-media-va-driver in docker

### ISSUE THREAD

**Issue by chrispazz** [MekayelAnik/ispyagentdvr-docker#6]
Hello,
is it possibile to add

intel-media-va-driver

to this docker image?
It is needed to use VAAPI HW acceleration on Synology NAS.
I added it by docker console and it is working out of the box selecting VAAPI in AgentDVR settings.

Thank you

**Comment by MekayelAnik** [comment]
You are welcome. If you face any problem regarding this docker image, please let me know.
Regards

**Comment by TobiasKWF** [comment]
That would be great if you can add the intel-media-va-driver ... In the actual Version Agent v5.2.4.0 it runs perfect with a intel gpu after do manual in container apt-get update && apt-get install -y intel-media-va-driver 

Br Tobias

**Comment by chrispazz** [comment]
> @chrispazz Are you asking to add GPU driver in the image?

Exactly :)

**Comment by MekayelAnik** [comment]
> That would be great if you can add the intel-media-va-driver ... In the actual Version Agent v5.2.4.0 it runs perfect with a intel gpu after do manual in container apt-get update && apt-get install -y intel-media-va-driver
> 
> Br Tobias

Did it work doing so in the container?
I don't have Intel GPU in my linux machine. So I have to rely on u guys.

**Comment by MekayelAnik** [comment]
@chrispazz @TobiasKWF
Can you please try `docker pull mekayelanik/ispyagentdvr:gpu-hwaccel-latest` and let me know the update?

**Comment by TobiasKWF** [comment]
Thx i will check the next day... my fast try with the mekayelanik/ispyagentdvr:gpu-hwaccel-latest image it hangs at install ffmpeg6 ... With your "normal" image mekayelanik/ispyagentdvr:latest and a manual cli apt-get install intel-media-va-driver all works fine..

**Comment by MekayelAnik** [comment]
@TobiasKWF 
There was a problem with when I updated the "gpu-hwaccel-latest", so I took it down. Debian apt repository is broken for ffmpeg6.1.1-1. I have to do further tweaking.
In the mean time, please try the "gpu-hwaccel-5.2.4.0" it doesn't have the ffmpeg problem.

**Comment by TobiasKWF** [comment]
Allright will be tested the next days .... Yeah the device (Intel GPU) are mapped as --device /dev/dri:/dev/dri ... so the hole gpu is shared with the container...
