### ISSUE TITLE
Any chance VLC support is coming?

### ISSUE THREAD

**Issue by djbios** [MekayelAnik/ispyagentdvr-docker#8]
VLC cant be installed in container by simple `apt install vlc` due to dependencies issue

UPD: `vlc-bin` can be installed, but I guess Agent DVR needs some additional configuration to identify vlc path

**Comment by MekayelAnik** [comment]
@djbios I will try to add this in future.
Currently, I am very short in free time.
Please wait a few months. I will add the `vlc`.
Thanks for your query.

**Comment by MekayelAnik** [comment]
@djbios I have published an image with VLC binary.
can u please verify if this image works. I don't have a VLC camera

**Comment by djbios** [comment]
@MekayelAnik Thanks for the quick response.
The container is starting, but the web UI is stuck at:
![Monosnap Agent DVR Installer 2024-02-01 12-14-16](https://github.com/MekayelAnik/ispyagentdvr-docker/assets/11632032/7afe974a-3da0-4117-b68e-09f4f4661353)

**Comment by MekayelAnik** [comment]
@djbios Please have a loot again. The FFMPEG issue is solved and  vlc is added.
Please let me know the update.

**Comment by MekayelAnik** [comment]
@djbios Please have a look again: `docker pull mekayelanik/ispyagentdvr:vlc-support-latest`
The FFMPEG issue is solved and vlc is added.
Please let me know the update.

**Comment by djbios** [comment]
Working fine now, thanks! I guess it worth mentioning in the docs :)

**Comment by MekayelAnik** [comment]
@djbios thanks for the suggestion. I will add it in the docs.
Have u used/tested the **vlc** related features in AgentDVR? If you have please confim.

**Comment by djbios** [comment]
Yes, I've added VLC camera and its working

**Comment by MekayelAnik** [comment]
@djbios Thank you.
Regards
